---
- hosts: localhost
  connection: local
  vars_files:
    - ./credentials/nios.yml
  vars:
    - network_id: "10.0"
    - view: default
    - nios_provider:
        host: "{{ nios_host }}"
        username: "{{ nios_username }}"
        password: "{{ nios_password }}"

  tasks:
    - name: "Delete subnets on the {{ view }} network view"
      nios_network:
        network_view: "{{ view }}"
        network: "{{ item }}"
        state: absent
        provider: "{{nios_provider}}"
      with_items:
        - "{{ network_id }}.1.0/24"
        - "{{ network_id }}.2.0/24"
        - "{{ network_id }}.3.0/24"
        - "{{ network_id }}.4.0/24"
        - "{{ network_id }}.5.0/24"
        - "{{ network_id }}.6.0/24"
        - "{{ network_id }}.7.0/24"
        - "{{ network_id }}.8.0/24"

    - name: "Delete the network on the {{ view }} network view"
      nios_network:
        container: yes
        network_view: "{{ view }}"
        network: "{{network_id}}.0.0/16"
        state: absent
        provider: "{{nios_provider}}"

    - name: Delete the network view when not default
      nios_network_view:
        name: "{{ view }}"
        state: absent
        provider: "{{nios_provider}}"
      when: view != "default"
